apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data
  labels:
    type: local
    app: cassandra
  namespace: aai-cassandra
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-data
  persistentVolumeReclaimPolicy: Delete
