version: '3'
services:
  cassandra-1:
    hostname: cassandra-1
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_CLUSTER_NAME=aai-cluster
    expose:
      - 7000
      - 7001
#      - 7199 #JMX
      - 9042
      - 9160
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
#    networks:
#      - somenetwork

  cassandra-2:
    hostname: cassandra-2
    image: cassandra:latest
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-1
      - CASSANDRA_CLUSTER_NAME=aai-cluster
    expose:
      - 7000
      - 7001
#      - 7199 #JMX
      - 9042
      - 9160
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
#    networks:
#      - somenetwork
    depends_on:
      - "cassandra-1"

  cassandra-3:
    hostname: cassandra-3
    image: cassandra:latest
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-1
      - CASSANDRA_CLUSTER_NAME=aai-cluster
    expose:
      - 7000
      - 7001
#      - 7199 #JMX
      - 9042
      - 9160
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
#    networks:
#      - somenetwork
    depends_on:
      - "cassandra-1"

#  networks:
#    somenetwork:
#      external: true
