apiVersion: v1
kind: Service
metadata:
  name: dms-jetty-service
  namespace: objectify
spec:
  selector:
    app: dms-jetty
  ports:
    - name: http
      port: 8080 
      targetPort: 8080
    - name: data
      port: 9010
      targetPort: 9010
