#apiVersion: apps/v1beta2
apiVersion: v1
#kind: Deployment
kind: Pod
metadata:
  name: dms-jetty
  labels:
    app: dms-jetty
  namespace: objectify
spec:
  #replicas: 1
  #selector:
  #  matchLabels:
  #    app: dms-jetty
  #template:
  #  metadata:
  #    labels:
  #      app: dms-jetty
  #  spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: dms-jetty
        image: objectify/dms-jetty:2.7.3
        command: ["/bin/sh", "-c"]
        args: ["mkdir -p /persistent_volume/docRepo; sed -i 's/^\\(docRespositoryRootDir\\s*=\\s*\\).*$/\\1\\/persistent_volume\\/docRepo/' /var/lib/jetty/conf/config.ini; sleep 10; /docker-entrypoint.sh java -jar /usr/local/jetty/start.jar"]
        #resources:
        #  limits:
        #    memory: "1896Mi" #zmena 896Mi
        ports:
        - containerPort: 8080
        - containerPort: 9010
        volumeMounts:
          - name: dms-doc-repo
            mountPath: /persistent_volume
      volumes:
        - name: dms-doc-repo
          persistentVolumeClaim:
            claimName: dms-jetty-claim
