apiVersion: v1
kind: Pod
metadata:
  name: dms-mysql
  labels:
    name: dms-mysql
  namespace: objectify
spec:
  containers: 
    - name: dms-mysql
      image: mysql:latest
      args:
        - "--ignore-db-dir=lost+found"
      resources:
        limits:
          memory: "256Mi"
      env: 
      - name: "MYSQL_USER"
        value: "dms"
      - name: "MYSQL_PASSWORD"
        value: "XXXXXXXXXXXXXXXXX"
      - name: "MYSQL_DATABASE"
        value: "dms"
      - name: "MYSQL_ROOT_PASSWORD"
        value: "XXXXXXXXXXXXXXXXX"
      ports: 
      - containerPort: 3306
      volumeMounts:
        - name: dms-mysql-data
          mountPath: /var/lib/mysql
  volumes:
    - name: dms-mysql-data
      persistentVolumeClaim:
        claimName: dms-mysql-claim
#      emptyDir: {}
