apiVersion: v1
kind: Pod
metadata:
  name: dms-solr
  labels:
    name: dms-solr
  namespace: objectify
spec:
  securityContext:
    runAsUser: 8983
    fsGroup: 8983
  containers: 
    - name: dms-solr
      image: objectify/dms-solr:2.6.1
     # is limiting needed at all? 512 Mi is too little
      #resources:
    #    limits:
    #      memory: "512Mi"
      volumeMounts:
        - name: dms-solr-data
          mountPath: /opt/solr/server/solr/develCore/data
  volumes:
    - name: dms-solr-data
      persistentVolumeClaim:
        claimName: dms-solr-claim

