apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dms-mysql-claim
  namespace: objectify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dms-solr-claim
  namespace: objectify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dms-jetty-claim
  namespace: objectify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
